package com.idea.tools.dto;

import lombok.Data;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

@Data
public class ServerDto implements Comparable<ServerDto> {

    private static final Comparator<String> COMPARATOR = Comparator.nullsLast(String::compareToIgnoreCase);

    private String id;
    private String name;
    private ServerType type;
    private ConnectionType connectionType;
    private String host;
    private Integer port;
    private String login;
    private String password;
    @Deprecated
    private List<QueueDto> queues = new ArrayList<>();
    private List<DestinationDto> destinations = new ArrayList<>();

    private boolean nameIsAutogenerated = true;

    public List<QueueDto> getQueues() {
        return queues;
    }

    @Override
    public int compareTo(@NotNull ServerDto o) {
        return COMPARATOR.compare(name, o.name);
    }
}
